name: Test No 00001
favicon: null
layout_spectrum: 0.27256
typography_spectrum: 0.77
title: An introduction of sorts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffc4bc'
    - '#c492b3'
    - '#b53e47'
    - '#c20b5e'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
