name: Test No 00001
favicon: null
layout_spectrum: 0.5669335082639009
typography_spectrum: 0.794078097678721
title: An introduction of sorts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.19087668950669467
  lightness: 0.6440891965758055
  saturation: 0.9725946101825684
  rhythmicContrast: 0.793793385848403
purpose: []
